title: StartBootstrap Landing Page
description: A landing page powered by StartBootstrap free templates.

baseurl: /startbootstrap-landing-page

include:
  - _pages

permalink: https://theuiguru.github.io/startbootstrap-landing-page/blog/:year/:month/:day/:title
