title: Business Frontpage
description: A business home page starter template for Bootstrap 4 featuring marketing boxes and a full width image header.

baseurl: /startbootstrap-landing-page

include:
  - _pages

permalink: /blog/:year/:month/:day/:title
