title: StartBootstrap Landing Page
description: A landing page powered by StartBootstrap free templates.
markdown: kramdown
baseurl: /startbootstrap-landing-page
include:
  - _pages
permalink: /blog/:year/:month/:day/:title
